### ISSUE TITLE
missing cdp_profile variable

### ISSUE THREAD

**Issue by maxhardt** [cloudera-labs/terraform-cdp-modules#42]
Last tag with `cdp_profile` variable seems to be `v0.1.0`: https://github.com/cloudera-labs/terraform-cdp-modules/tree/v0.1.0/modules/terraform-cdp-aws-pre-reqs#input_cdp_profile

**Comment by jimright** [comment]
Hi @maxhardt,

This input variable was removed as it is no longer needed since switching to use the CDP Terrafrom Provider (from Ansible & CDP CLI in the previous 0.1.x tags). With the CDP Terraform provider to specify the CDP profile to use you can either:

1.  Set the profile name in the CDP provider configuration in the Terraform root module (e.g. [main.tf of the quickstarts](https://github.com/cloudera-labs/cdp-tf-quickstarts/blob/main/aws/main.tfl)) as shown below.
```
provider "cdp" {
  cdp_profile = "customprofile"
}
```
2. Set the `CDP_PROFILE` environment variable in your terminal, e.g.
```
export CDP_PROFILE=customprofile
```
I generally use the second option. More details about the methods of authentication for the CDP provider can be found in the Terraform docs - https://registry.terraform.io/providers/cloudera/cdp/latest/docs#authentication.


Some more context about the input variable - previously, in the v0.1.x tags, we used CDP CLI to determine account ids for used in the AWS policy documents and Ansible to deploy the CDP environment. The `cdp_profile` input variable was the best way to ensure the same CDP credentials were used for both CLI and Ansible modules.

**Comment by maxhardt** [comment]
Thanks for the detailed answer @jimright! I was aware of the provider changes but was missing an example where/how to set it.

May I suggest:
- Adding `cdp_profile` provider config to quickstarts root module as a variable.
- Updating README of quickstarts/modules repos with the 2 options above.

This may help prevent people from asking similar questions. What do you think?

**Comment by jimright** [comment]
> May I suggest:
> 
> * Adding `cdp_profile` provider config to quickstarts root module as a variable.
> * Updating README of quickstarts/modules repos with the 2 options above.
> 
> This may help prevent people from asking similar questions. What do you think?

Definitely a README entry is warranted.

I'm not so sure about (re-)introducing a `cdp_profile` variable; I don't want to prescribe the method to set the profile. However I think we might be able to set it to default value of null and mention that the variable exists in the README if needed.

@balazsgaspar - any thoughts/objections on re-introducing the `cdp_profile` variable and using just in the provider configuration in main.tf  of the quickstart?

**Comment by jimright** [comment]
Hi @maxhardt,

We've added some notes about CDP authentication, including how to specify the profile, in the [DEVELOPMENT.md](https://github.com/cloudera-labs/terraform-cdp-modules/blob/main/DEVELOPMENT.md#notes-on-cdp-authentication) file and put a reference to this from readme.

If those notes look ok to you then we will close out this issue.

**Comment by maxhardt** [comment]
Looks good to me thanks all, closing this issue.
